### ISSUE TITLE
The mod isn't available for 1.16

### ISSUE THREAD

**Issue by Sshmoob** [PssbleTrngle/TinkersJEI#4]
I would like to request that the mod should be ported to 1.16, now that t-construct is available on 1.16.

**Comment by BeansBeefBroccoli** [comment]
It is unessecary to update this as all the features from this are in the base mod

**Comment by BeansBeefBroccoli** [comment]
Plus, I already did this [here](https://github.com/PssbleTrngle/TinkersJEI/issues/3).
